from docx import Document
from docx.shared import Inches  # resize picture


document = Document()

# ''' Add picture to the document'''
document.add_picture('hellsing 2.jpg',
                     width=Inches(1.2))

#'''Add information to document'''
name = input('what is your name:')
phone_no = input('what is your telephone number:')
email = input('what is your email address:')
document.add_paragraph(name + '|' + phone_no + '|' + email)

# About me
document.add_heading('About me')
about_me = input('Tell us about yourself: ')
document.add_paragraph(about_me)

# work experience
document.add_heading('Work Experience')
p = document.add_paragraph()

company = input("Enter company:")
from_date = input('From Date:')
to_date = input('To date:')

# add text to existing paragraph
p.add_run(company + ' '). bold = True
p.add_run(from_date + ' - ' + to_date + '\n').italic

experience_details = input('decribe your experience at ' + company + ':')
p.add_run(experience_details)

# more work experience
while True:
    more_work_experience = input(
        'Do you have more work experiences? Yes or No: ')
    if more_work_experience.lower() == 'yes':
        p = document.add_paragraph()

        company = input("Enter company:")
        from_date = input('From Date:')
        to_date = input('To date:')

        # add text to existing paragraph
        p.add_run(company + ' '). bold = True
        p.add_run(from_date + '_' + to_date + '\n').italic

        experience_details = input('decribe your experience at ' + company)
        p.add_run(experience_details)
    else:
        break

    # Skills
document.add_heading('Skills')
any_skills = input('Enter skills: ')
document.add_paragraph(any_skills)
p.style = 'List Bullet'

while True:
    skills = input('Do you have any other skills? Yes or No: ')
    if skills.lower() == 'yes':
        any_skills = input("Enter Skill:")
        document.add_paragraph(any_skills)
        p.style = 'List Bullet'
    else:
        break
    # footer
    section = document.sections[0]
    footer = section.footer
    p = footer.paragraphs[0]
    p.text = "Vc generated by knowledge gained from amigoscode"
document.save('cv.docx')
